### ISSUE TITLE
Bullet time

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/hypertools#124]
Want to add a `bullettime` animation option that, if true, overrides `chemtrails` and `precog` by setting both to True?  (If false, it's ignored)

**Comment by andrewheusser** [comment]
:) sure! the way i've set it up you can use either chemtrails=True and precog=True, or bullettime=True and it will do the same thing

**Comment by andrewheusser** [comment]
added on 04c79ea

**Comment by jeremymanning** [comment]
https://youtu.be/KNrSNcaYiZg
