### ISSUE TITLE
Should the rotation mattrix be orthonormal?

### ISSUE THREAD

**Issue by MechCoder** [ContextLab/hypertools#135]
I was reading the example (http://hypertools.readthedocs.io/en/latest/auto_examples/plot_procrustes.html#sphx-glr-auto-examples-plot-procrustes-py)

Shouldn't the rotation matrix be orthonormal? See https://en.wikipedia.org/wiki/Rotation_matrix#Properties_of_a_rotation_matrix

**Comment by andrewheusser** [comment]
yes, totally correct.  good catch! patched on b369330
