### ISSUE TITLE
Mutable Default Arguments in some Hypertools Functions

### ISSUE THREAD

**Issue by rarredon** [ContextLab/hypertools#140]
I noticed there are some functions with mutable default arguments, for example, `hypertools.plot` has the kwarg `model_params={}`. This is a [common gotcha](http://python-guide-pt-br.readthedocs.io/en/latest/writing/gotchas/) in Python programming. While I don't think there's any issues with it now, this could potentially cause problems later. I recommend replacing the default argument with `None` and then checking if it's `None` to change it out accordingly.

**Comment by rarredon** [comment]
I can work on fixing this issue.

**Comment by andrewheusser** [comment]
@rarredon that would be fantastic... thanks for the link! :)

**Comment by jeremymanning** [comment]
@rarredon and/or @andrewheusser can you provide a status update on this issue?

**Comment by andrewheusser** [comment]
this is fixed in 0.4.0 - thanks @rarredon for pointing it out 🥇
