### ISSUE TITLE
UserWarning thrown when importing hypertools in jupyter notebook

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/hypertools#145]
When importing hypertools in a jupyter notebook (`import hypertools as hyp`), the following warning is thrown:

```
/opt/conda/lib/python3.6/site-packages/matplotlib/__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
```

Proposed fix: suppress this warning within hypertools (more info [here](https://docs.python.org/2/library/warnings.html))

**Comment by andrewheusser** [comment]
@jeremymanning hmmm i'm having trouble replicating this error.  can you verify that you are running version 0.3.0?

**Comment by andrewheusser** [comment]
also, which matplotlib version?

**Comment by jeremymanning** [comment]
here's the version info (all of this is from the [MIND Docker Container](https://github.com/Summer-MIND/mind-tools)

```
root@2ca632e4000c:/# pip show matplotlib
Name: matplotlib
Version: 2.0.2
Summary: Python plotting package
Home-page: http://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: BSD
Location: /opt/conda/lib/python3.6/site-packages
Requires: numpy, six, python-dateutil, pytz, cycler, pyparsing
root@2ca632e4000c:/# pip show hypertools
Name: hypertools
Version: 0.3.0
Summary: A python package for visualizing and manipulating high-dimensional data
Home-page: https://github.com/ContextLab/hypertools
Author: Contextual Dynamics Lab
Author-email: contextualdynamics@gmail.com
License: MIT
Location: /opt/conda/lib/python3.6/site-packages
Requires: scipy, seaborn, PPCA, scikit-learn, future, requests, matplotlib, numpy, pandas
root@2ca632e4000c:/# pip show jupyter   
Name: jupyter
Version: 1.0.0
Summary: Jupyter metapackage. Install all the Jupyter components in one go.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
License: BSD
Location: /opt/conda/lib/python3.6/site-packages
Requires: 

```

**Comment by andrewheusser** [comment]
got it, thanks.  I was able to replicate this by importing hypertools and seaborn in the same notebook.  They both rely on matplotlib and both attempt to change the default matplotlib backend.  
The issue comes when any package imports matplotlib with a particular backend. after that happens hypertools is not able to switch it.

I can suppress the warning, but it also may be informative to throw a different error that says that hypertools couldn't switch the matplotlib backend, so it may not work properly.  Currently, we switch the backend from `Agg` to `TkAgg` because if you don't, any you are using matplotlib 2.0, when attempting to drag the 3D plots, its super choppy for whatever reason.

**Comment by jeremymanning** [comment]
But don't we import seaborn from within hypertools?  And if so, what's the purpose of the warning?

**Comment by andrewheusser** [comment]
The purpose of the warning is to say that the matplotlib backend was not switched.

hmm, yea we do import seaborn, but we import matplotlib before anything else, and I think seaborn supresses the warning. This is in our top level __init__.py script:

```
import matplotlib as mpl
mpl.use('TkAgg')
```

In the jupyter notebook you tried, do you import seaborn or anything else relying on matplotlib before hypertools?

**Comment by jeremymanning** [comment]
Ah-- it seems like this could be it.  I get the warning when importing one or both of `seaborn` and `nilearn.plotting`.  The warning goes away when both of those are removed.

However, if both seaborn and nilearn mess with the matplotlib backend (but don't output warnings when they are imported together), I think hypertools should follow that behavior as well (by suppressing this warning).

Basically, my thinking is that I don't see the warning being useful, but it makes hypertools look slightly messier.

Side question: was the `mpl.use('TkAgg')` need to get fonts to export correctly?

**Comment by jeremymanning** [comment]
Another note: it doesn't seem to matter if hypertools is imported first or last.

**Comment by andrewheusser** [comment]
this is fixed on 9de0a517486e1e2acf8eb4532d546d59db423e82. i added:

```
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    mpl.use('TkAgg')
```

**Comment by jeremymanning** [comment]
🍾

**Comment by andrewheusser** [comment]
ill push this to pip as 0.3.1

**Comment by jeremymanning** [comment]
thanks!
