### ISSUE TITLE
Not able to install in python 3.6

### ISSUE THREAD

**Issue by renjithmadhavan** [ContextLab/hypertools#150]
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-48afb9e37bd3> in <module>()
----> 1 import hypertools

ImportError: No module named hypertools`

**Comment by renjithmadhavan** [comment]
Install seems to be good though.

`(python3) renjith@dlp20db:~$ sudo pip3 install hypertools
[sudo] password for renjith:
The directory '/home/renjith/.cache/pip/http' or its parent directory is not own                                                                                                              ed by the current user and the cache has been disabled. Please check the permiss                                                                                                              ions and owner of that directory. If executing pip with sudo, you may want sudo'                                                                                                              s -H flag.
The directory '/home/renjith/.cache/pip' or its parent directory is not owned by                                                                                                               the current user and caching wheels has been disabled. check the permissions an                                                                                                              d owner of that directory. If executing pip with sudo, you may want sudo's -H fl                                                                                                              ag.
Collecting hypertools
  Downloading hypertools-0.3.1.tar.gz
Collecting PPCA>=0.0.2 (from hypertools)
  Downloading ppca-0.0.2.tar.gz
Collecting scikit-learn>=0.18.1 (from hypertools)
  Downloading scikit_learn-0.19.0-cp35-cp35m-manylinux1_x86_64.whl (12.3MB)
    100% |████████████████████████████████| 12.3MB 221kB/s
Collecting pandas>=0.18.0 (from hypertools)
  Downloading pandas-0.20.3-cp35-cp35m-manylinux1_x86_64.whl (24.0MB)
    100% |████████████████████████████████| 24.0MB 114kB/s
Collecting seaborn>=0.7.1 (from hypertools)
  Downloading seaborn-0.8.1.tar.gz (178kB)
    100% |████████████████████████████████| 184kB 12.0MB/s
Collecting matplotlib>=1.5.1 (from hypertools)
  Downloading matplotlib-2.0.2-cp35-cp35m-manylinux1_x86_64.whl (14.6MB)
    100% |████████████████████████████████| 14.6MB 190kB/s
Collecting scipy>=0.17.1 (from hypertools)
  Downloading scipy-0.19.1-cp35-cp35m-manylinux1_x86_64.whl (47.9MB)
    100% |████████████████████████████████| 47.9MB 57kB/s
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.5/dist-pa                                                                                                              ckages (from hypertools)
Collecting future (from hypertools)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 2.2MB/s
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from                                                                                                               hypertools)
Collecting pytz>=2011k (from pandas>=0.18.0->hypertools)
  Downloading pytz-2017.2-py2.py3-none-any.whl (484kB)
    100% |████████████████████████████████| 491kB 3.7MB/s
Requirement already satisfied: python-dateutil>=2 in /usr/local/lib/python3.5/di                                                                                                              st-packages (from pandas>=0.18.0->hypertools)
Collecting cycler>=0.10 (from matplotlib>=1.5.1->hypertools)
  Downloading cycler-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6                                                                                                               in /usr/local/lib/python3.5/dist-packages (from matplotlib>=1.5.1->hypertools)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.5/dist-packag                                                                                                              es (from matplotlib>=1.5.1->hypertools)
Installing collected packages: scipy, PPCA, scikit-learn, pytz, pandas, cycler,                                                                                                               matplotlib, seaborn, future, hypertools
  Running setup.py install for PPCA ... done
  Running setup.py install for seaborn ... done
  Running setup.py install for future ... done
  Running setup.py install for hypertools ... done
Successfully installed PPCA-0.0.2 cycler-0.10.0 future-0.16.0 hypertools-0.3.1 m                                                                                                              atplotlib-2.0.2 pandas-0.20.3 pytz-2017.2 scikit-learn-0.19.0 scipy-0.19.1 seabo                                                                                                              rn-0.8.1
(python3) `

**Comment by andrewheusser** [comment]
hmmm, strange. it runs fine on 3.6 on our travis setup.  what environment are you trying to run it in? i.e. jupyter notebook, ipython etc?

**Comment by renjithmadhavan** [comment]
I was using conda. 
Its my mistake . ( too many envs ).

Working now. Excited to try "hypertools".

**Comment by andrewheusser** [comment]
:) nice! hope you find it useful
