### ISSUE TITLE
add brainIAK citation for SRM module

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/hypertools#151]
From the BrainIAK readme: 

```
Please cite BrainIAK in your publications as: "Brain Imaging Analysis Kit, http://brainiak.org." Additionally, if you use RRIDs to identify resources, please mention BrainIAK as "Brain Imaging Analysis Kit, RRID:SCR_014824". Finally, please cite the publications referenced in the documentation of the BrainIAK modules you use, e.g., SRM.
https://github.com/IntelPNI/brainiak
```

The most obvious place, I think, would be to paste in the reference here: http://hypertools.readthedocs.io/en/latest/hypertools.tools.align.html#hypertools.tools.align

**Comment by andrewheusser** [comment]
added citation and github link to the docstring on a3483415f581db4a660f197cca88278e7247f38.

**Comment by andrewheusser** [comment]
updated the docstring: http://hypertools.readthedocs.io/en/latest/hypertools.tools.align.html#hypertools.tools.align

@jeremymanning can you close if satisfied?

**Comment by jeremymanning** [comment]
👍
