### ISSUE TITLE
tutorials

### ISSUE THREAD

**Issue by andrewheusser** [ContextLab/hypertools#160]
To help users get started with the tutorial, it would be nice to have a set of tutorials that go over the main features (something like this: http://cdl-quail.readthedocs.io/en/latest/tutorial.html).  Each tutorial can be a separate Jupyter notebook. 

- Notebook titles should written in a markdown cell using `#` to make it large
- Subtitles should be written in a markdown cell using `##` to make them a bit smaller
- Descriptions should be written in a markdown cell with no pound sign
- Code examples should in in python

 See [here](https://github.com/ContextLab/quail/blob/master/docs/tutorial/basic_analyze_and_plot.ipynb) for an example of how to format as described above.

Here is what I'm thinking. Please check these off as you go so we can keep track, and if you run into any issues, leave a message on this thread and move on to the next thing.

1. A notebook highlighting the `hyp.plot` function - examples of:

- [x] importing the toolbox
- [x] loading in some example data i.e. `mushrooms`
- [x] plotting with defaults i.e. `geo = hyp.plot(data, '.')`
- [x] plotting in 2D (setting `ndims=2`)
- [x] plotting with different dimensionality reduction (TSNE)
- [x] plotting with grouping (setting `group=list_of_group_labels`)
- [x] plotting with labels (labelling a subset of points to `labels`)
- [x] plotting with a legend (setting `legend=True`)
- [x] interpolating missing data (set some of the points to nan)
- [x] plotting with clusters (setting `n_clusters`)
- [x] plotting with normalization (setting normalize='within')
- [x] plotting with alignment ([example](http://hypertools.readthedocs.io/en/latest/auto_examples/plot_align.html#sphx-glr-auto-examples-plot-align-py))
- [x] saving a plot (`save_path=something`)

2. A notebook highlighting the `hyp.analyze` function. examples of:

- [x] importing the toolbox
- [x] loading in some example data i.e. `weights_avg`
- [x] an example normalizing the data
- [x] normalizing + reducing
- [x] normalizing + reducing + aligning 

3. A notebook highlighting `hyp.normalize` examples of:
- [x] importing the toolbox
- [x] generate some synthetic data (see [this](http://hypertools.readthedocs.io/en/latest/auto_examples/plot_normalize.html#sphx-glr-auto-examples-plot-normalize-py) example)
- [x] normalize `within`
- [x] normalizing `across`
- [x] normalizing by `row`

4. A notebook highlighting dimensionality reduction with `hyp.reduce`. examples of:

- [x] importing the toolbox
- [x] loading in some example data i.e. `mushrooms`
- [x] reducing a single array
- [x] reducing a list of arrays
- [x] reducing a list of arrays with TSNE
- [x] reducing a list of arrays where ndims>3
- [x] reducing a list of arrays and tweaking the model parameters using the dictionary syntax

5. A notebook highlighting `hyp.align`. examples of:

- [x] importing the toolbox
- [x] loading in some example data i.e. `weights`
- [x] plotting two unaligned datasets (using the line plot not '.')
- [x] plotting two aligned datasets aligned with hyperalignment
- [x] plotting two aligned datasets aligned with SRM

6. A notebook highlighting `hyp.cluster` examples of:

- [x] importing the toolbox
- [x] loading in some example data i.e. `mushrooms`
- [x] return cluster labels with default args
- [x] setting `n_clusters` equal to something other than the default
- [x] using a different cluster model e.g. `cluster='AgglomerativeClustering'`

7. A notebook highlighting the `geo` class. examples of:

- [x] importing the toolbox
- [x] loading in some example data i.e. `mushrooms`
- [x] plot the data and generate a `geo`
- [x] description of each of the fields (see [here](http://hypertools.readthedocs.io/en/latest/hypertools.DataGeometry.html#hypertools.DataGeometry) for API description)
- [x] using `geo.plot`
- [x] transforming new data `geo.transform(new_data)`
- [x] saving data with `geo.save`

**Comment by jeremymanning** [comment]
Sounds like a great idea!  :+1:

These should probably go into [this repo](https://github.com/ContextLab/hypertools-paper-notebooks), and we should consider renaming that repository to `hypertools-examples` or simililar (and then we should update all links to the original notebook).

The reason to include these in a separate repo is to prevent users/developers from having to download extra stuff if they just want to work on the code.  (But they are also small files...so I'm open to alternative ideas and/or including them in this repo if there's a compelling reason.)

**Comment by andrewheusser** [comment]
For `quail`, I have these in the docs folder, because you can autocompile notebooks into a websitesee [here](http://cdl-quail.readthedocs.io/en/latest/tutorial.html).

**Comment by jeremymanning** [comment]
That looks perfect-- let's do that!

**Comment by andrewheusser** [comment]
I've finished and push edits on 4/7 tutorials. Will finish the rest today/tomorrow!
