### ISSUE TITLE
expose `format_data` to user via `helpers`

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/hypertools#167]
The `format_data` function is useful!  Let's expose it to users via `hyp.tools.as_np` (with PPCA='False' by default).

**Comment by jeremymanning** [comment]
hey @andrewheusser-- I implemented this change in this branch: https://github.com/ContextLab/hypertools/tree/expose_format_data

could you please:
- take a look
- add a doc string so that it appears in our API documentation
- if the changes look good, pull the branch into master
- update the version number (minor version += 1) and push to pip

**Comment by andrewheusser** [comment]
should be good! see #168
