### ISSUE TITLE
Animate not working in 64 bit anaconda install (python 2.7)

### ISSUE THREAD

**Issue by svadams** [ContextLab/hypertools#172]
I am using hypertools version 0.4.0

If I do a load and basic plot of the mushroom dataset as follows:

data = pd.read_csv('./mushrooms.csv')
hyp.plot(data, '.', animate=True)

I get the error message:

 File "D:\Anaconda2_64\lib\site-packages\hypertools\plot\draw.py", line 430, in
   assert x[0].shape[1] is 3, "Animations are currently only supported for 3d plots.
AssertionError: Animations are currently only supported for 3d plots.

It works fine in 32 bit anaconda.

**Comment by svadams** [comment]
Sorry...should have added that I'm on Windows 7 !

**Comment by andrewheusser** [comment]
hmmm, that's an odd bug.  thanks for bringing it to our attention! will look into it

**Comment by andrewheusser** [comment]
hi @svadams this issue should be fixed now. please reopen if its not, thanks!
