### ISSUE TITLE
arranging hypertools plots into a grid of subplots

### ISSUE THREAD

**Issue by mhlr** [ContextLab/hypertools#184]
How can I arrange multiple hypertools plots into a grid of subplots?

**Comment by andrewheusser** [comment]
Hi @mhlr - we are adding an `ax` argument to the plot function in the next release coming out soon, which should make this easy.

**Comment by mhlr** [comment]
@andrewheusser Thanks, that is great! By soon do you mean days, weeks, or months?

**Comment by andrewheusser** [comment]
@mhlr Most of the code for the release is almost there, so it should be functional if you don't mind installing from the master branch.  I'll have that done within a week, and I'll let you know when the ax param has been added, unless you'd like to take a stab at it.  The "official" 0.5.0 release (e.g. push to pip) will probably happen sometime in Feb.

**Comment by andrewheusser** [comment]
Hi @mhlr - this is now implemented on the text-features branch.  i'll be working to get the 0.5.0 release out next week if you want to wait until it is officially supported!
