### ISSUE TITLE
interference with seaborn/matplotlib settings

### ISSUE THREAD

**Issue by andrewheusser** [ContextLab/hypertools#210]
When the plot function is called, hypertools modifies seaborn/matplotlib settings, causing plots run after a hypertools plot function call to change.  I believe it's caused by calling `set_palette` and `set_style` inside the plot function, which we should remove and modify the plot instance directly

**Comment by paxtonfitzpatrick** [comment]
Duplicated by #243 (oops!) and fixed in [v0.7.0](https://github.com/ContextLab/hypertools/releases/tag/v0.7.0) 

Implemented here:
https://github.com/ContextLab/hypertools/blob/e7b744666bf20e352d66f0713deab264a4473294/hypertools/plot/backend.py#L798-L861
