### ISSUE TITLE
Plotting animations do not seem to be compatible with Jupyter Notebook 7

### ISSUE THREAD

**Issue by ljchang** [ContextLab/hypertools#261]
There was a major update to Jupyter Notebook/Lab from Version 6 to[ Version 7](https://jupyter-notebook.readthedocs.io/en/latest/notebook_7_features.html#debugger) this past year.

The hypertools helper functions that deal with backends when plotting animations do not seem to be compatible with the new version of jupyter notebook.

![Screenshot 2024-03-11 at 7 17 29 PM](https://github.com/ContextLab/hypertools/assets/2993338/fb6504b3-c717-4de0-8df1-a8a418234360)

Everything works when I switch to using the old version (i.e., nbclassic).

Just wanted to bring this to your attention.  Thanks!

**Comment by paxtonfitzpatrick** [comment]
@ljchang this should now be fixed on master if you'd like to try it out! 
```
pip install git+https://github.com/ContextLab/hypertools.git
```

Animated & interactive plots should now automatically work in both "classic" notebooks and Notebook v7+, as well as in JupyterLab. 

One quick thing to note is that if you run your Jupyter notebook/lab server from a different environment than your IPython kernel, you'll also need to `pip install ipympl` into the notebook server's environment, then shutdown and re-launch the server. This will provide the JS components that the notebook/lab frontend needs to display interactive plots.

I'm gonna close this for now, but if you run into any more issues please feel free to re-open! Thanks again!
