### ISSUE TITLE
add an ipython notebooks to this project (somehow)

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/hypertools#68]
I'd like us to link our ipython notebook examples with this project somehow.  Some ideas:

+ Add a folder with the ipython notebooks
+ Host the notebooks somewhere else and add a link to that somewhere else in the readme
+ Add links to the ipython notebooks in our hypertools

Another issue we'll need to solve as part of this is to make sure that any links embedded in the notebooks are relative and/or universal (rather than being hard-coded local links that will only work on one computer).

Ideally we would have some or all of the notebooks ready as part of our main release on Friday-- I think they'd help people understand how to use different features and showcase some additional plot styles and ideas.  However, we could also add these examples in after the main release as they are ready for sharing.

@lucywowen and I also discussed some new notebook ideas this morning, and in various other meetings we've had more ideas too.  It might be helpful to maintain a repository of ipython notebooks of different "data explorations and visualizations," e.g. as part of this repository, our sampleData repository, or a new repository.  We could then branch off those demos into full-fledged projects (e.g. @andrewheusser's Indiana Jones analyses), etc.

Thoughts on the best way to do this?

**Comment by andrewheusser** [comment]
leaving this open until we add tweets

**Comment by andrewheusser** [comment]
closing this and reopening in the notebook repo
