### ISSUE TITLE
data visualization examples gallery

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/hypertools#77]
Let's come up with a way to have users submit neat looking HyperTools examples along with a paragraph or so of text describing what they've visualized.  Depending on how many we get, we can either show all of them, or pick the coolest ones and (with credit) show them off to the world.

**Comment by jcheong0428** [comment]
Hi guys - I'm thinking of trying out Hypertools for our tv-study data with
facial expressions like the one you did with the movie example in the
paper.
Any chance one of you would be willing to give me a quick tutorial perhaps
today or tomorrow?
I can prepare my data in the right format before coming over too.
Thanks for making such a cool toolbox!

Best,
Jin

**Comment by jeremymanning** [comment]
Hey @jcheong0428-- let us know if Andy's email cleared things up or if you're still looking for more help once you've tried it out.

**Comment by jeremymanning** [comment]
I think this is solved via the examples gallery... closing...
