### ISSUE TITLE
streaming data

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/hypertools#78]
I'd also like us to re-visit support for streaming data.  This could be a really powerful way of doing biofeedback experiments, or visualizing any sort of data stream (twitter data, stock market data, weather, etc.).  Now that we have the main toolbox in place, I'd like us to do some brainstorming to try to come up with an elegant and ideally not-too-difficult way of implementing streaming support.

https://www.youtube.com/watch?v=jyaLZHiJJnE

**Comment by andrewheusser** [comment]
documented this on the projects page for the 0.2.0 release, closing here :)
