### ISSUE TITLE
for matplotlib>=2.0.0, labels is broken

### ISSUE THREAD

**Issue by andrewheusser** [ContextLab/hypertools#79]
Something changed in the 2.0 release that breaks labels, and causes the 3d rotating to be janky.

**Comment by andrewheusser** [comment]
we can require <=2.0.0 for now, and then check out the matplotlib 2.0 to see what changed

**Comment by jeremymanning** [comment]
https://www.youtube.com/watch?v=qXNqEURmKtA

noooo!  yeah, we should explore this and make a note on the readme for now explaining why we're requiring matplotlib earlier than 2.0.

**Comment by jeremymanning** [comment]
we can open a matplotlib issue too, if warranted

**Comment by jeremymanning** [comment]
(also: nice catch!)

**Comment by andrewheusser** [comment]
setting the matplotlib backend to "TkAgg" seems to fix this problem. Tkinter is "Python's de-facto standard GUI (Graphical User Interface) package" and should come preinstalled on osx/linux machines.

**Comment by andrewheusser** [comment]
0.1.5 supports python 3 and matplotlib 2.0

**Comment by stonebig** [comment]
didn't you forgot to remove the limitation inside setup.py ? I still see:

 'matplotlib>=1.5.1,<2.0',
