### ISSUE TITLE
resampled trajectories

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/hypertools#87]
It'd be nice to have a flag (disabled by default) to enable users to plot "smoothed" versions of trajectories, like the ones computed during animations.  This could be implemented using something like `resample=1` by default, and then if `resample` > 1 the trajectory would be resampled at `resample` times the original samplerate.  (This would enable users to either upsample or downsample easily.)

This functionality also could be exposed in a `hyp.tools.resample` function to enable users to gain direct access to the resampled data.

**Comment by andrewheusser** [comment]
all for this, but i have a list of other possible features for a second release on the 'projects' page.  maybe we can meet and decide on what is the priority, and then i'll add those as issues?

**Comment by andrewheusser** [comment]
added to v2 features list
