### ISSUE TITLE
plot styling consistency

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/hypertools#89]
the plot styles differ between static and animated plots.  specifically, static plots appear on gridded and numbered axes that are shaded, whereas animated plots appear enclosed within a black cube with no shading or numbering.

static:
![temperature2](https://cloud.githubusercontent.com/assets/9030494/25043147/cefb0ff4-20eb-11e7-933b-6dfabae3b380.png)

animated:
![temps](https://cloud.githubusercontent.com/assets/9030494/25043423/db8aaf70-20ed-11e7-9016-259de607d612.gif)

i think we should strive to follow tufte's laws of data-ink:

1.) above all else show the data
2.) maximize the data-ink ratio
3.) erase non-data-ink
4.) erase redundant data-ink
5.) revise and edit

to this end, i propose that we remove the grids and shading from static plots, so that they match the visual appearance of a frame of the animated plots (e.g. show the data as a trajectory or point cloud enclosed within a wireframe cube).

i also propose that we make the following changes to these "data cubes" to better adhere to tufte's laws:

1.) make the default line widths for data trajectories thinner
2.) make the cube's lines gray or increase alpha transparency, and possibly thinner

**Comment by jeremymanning** [comment]
another side issue that came up as part of addressing [this issue](https://github.com/ContextLab/hypertools/issues/86#issuecomment-294294384) is that for static plots the axis bounds are tight around the data, but for the animated plots the axes are zoomed out.  we should keep those consistent.

the general rule i'm hoping for here is that the static and animated plots should look identical other than that the animated plots should "move."

**Comment by jeremymanning** [comment]
the current separation of `animate` and `plot` is inefficient and results in a lot of doubled code.  instead, we should replace these with a single `draw` function (that accepts an animate flag).  if 3d, draw a cube and then plot the data.  if 2d, draw a square and then plot the data.  if animated, spin the camera or evolve the animation as specified.

i suggest using `animate.py` as the baseline for this function, since we're going to be moving forward with the animated plot styles anyway.

**Comment by andrewheusser** [comment]
new style for 0.2.0 @jeremymanning what do you think?  if all set, we can close this because its implemented on the branch (`args-refactor`) that i'll push before the mozilla sprint

![figure_1](https://cloud.githubusercontent.com/assets/6596567/26462807/3ff82618-4150-11e7-8dd4-067c38198cf6.png)

**Comment by jeremymanning** [comment]
That looks awesome!

**Comment by jeremymanning** [comment]
actually...i just took a quick look at the code and am re-opening.  for 2d plots, i think we need an analog of plot_cube that plots a square around the data...right?  so that 2d plots also have the same style?  that way we could also have 2d animations (where spinning is always off, but we could support chemtrails and precog).

@andrewheusser should we open a separate issue for the 2d plot styles, or is this sufficiently similar to be covered under the same framework now (e.g. within draw.py)?

**Comment by andrewheusser** [comment]
2d plots are also implemented, i just need to push. animated 2d plots and the precog are new features, so i'll open up 2 separate issues for those fellas

<img width="642" alt="screen shot 2017-05-25 at 3 21 16 pm" src="https://cloud.githubusercontent.com/assets/6596567/26466750/da280aac-415d-11e7-9368-57863e43da0b.png">

**Comment by jeremymanning** [comment]
Nice :+1:
