### ISSUE TITLE
allow legend to be computed from group kwarg

### ISSUE THREAD

**Issue by andrewheusser** [ContextLab/hypertools#97]
Currently, legends are set explicitly by passing a list to the `plot` function.  However, they could also be set automatically by passing a `group` list to the `legend` kwarg

e.g.
`hyp.plot(data, group=labels, legend=labels)`

**Comment by jeremymanning** [comment]
If `legend=True` and `group` is specified, set the legend labels to the group labels.

If `legend=True` and there are no groups, each list element gets a numerical label in the legend (Dataset 1, Dataset 2, etc.).

If `legend=False` (default) don't show a legend

If `legend=labels` (where `labels` is a list of strings), set the legend labels to `labels`.

**Comment by alysivji** [comment]
I'm at the Mozilla sprint in Chicago. This seems like a good project to get started with.

I'm setting up my env so I can play around with hypertools and then I will work on this issue.

**Comment by jeremymanning** [comment]
Welcome @alysivji!

**Comment by andrewheusser** [comment]
@alysivji - awesome!  let us know how we can help via gitter: https://gitter.im/hypertools/Lobby
